version: "3"
services:
  trainer_profile:
    build:
      context: .
      dockerfile: ./trainer/Dockerfile
    image: cau777/aipg-trainer
    privileged: true
  versions:
    build:
      context: .
      dockerfile: ./versions_server/Dockerfile
    ports:
      - "8000:80"
    image: cau777/aipg-versions-controller