[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["rlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.81"
codebase = { path = "../codebase" }
once_cell = "1.15.0"