[package]
name = "versions_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21", features = ["full"] }
warp = "0.3"
codebase = { path = "../codebase" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.*"
uuid = { version = "1.2.2", features = ["v4"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1